paths:
  uploads: uploads
  static: ''
editor:
  default_path: https://github.com/lgchemer/grammr/tree/master/fiu-frontend
timezone: America/New_York
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
build:
  install_command: " "
  build_command: cd fiu-frontend && npm run build
  output_path: fiu-frontend/.next
  source: fiu-frontend